import React, { useState } from 'react';
import { MOCK_EVIDENCE_CHAIN, MOCK_RESEARCH_ITEMS } from '../data/mockData';
import type { ResearchItem } from '../data/mockData';
import { EvidenceModal } from '../components/EvidenceModal';
import { Layers, CheckCircle2, ExternalLink, ArrowUpRight } from 'lucide-react';

export const EvidenceExplorer: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'Chain' | 'Sources'>('Chain');
  const [selectedEvidenceItem, setSelectedEvidenceItem] = useState<ResearchItem | null>(null);

  const sources = [
    { name: 'Digital India Land Records Modernization Programme (DILRMP)', type: 'National Registry', year: 2026, status: 'Verified Official Schema', impact: 'High', linkedId: 'res-104' },
    { name: 'National Remote Sensing Centre (NRSC / ISRO Bhuvan)', type: 'Spatial GIS', year: 2025, status: 'Satellite Vector Synced', impact: 'High', linkedId: 'res-102' },
    { name: 'NITI Aayog Land Governance Advisory Group', type: 'Policy Body', year: 2025, status: 'Draft Framework', impact: 'Medium', linkedId: 'res-105' },
    { name: 'IIT Madras Land Governance Policy Research Lab', type: 'Academic Institution', year: 2026, status: 'Peer Reviewed Paper', impact: 'High', linkedId: 'res-101' },
  ];

  const handleOpenSourceModal = (linkedId: string) => {
    const item = MOCK_RESEARCH_ITEMS.find(r => r.id === linkedId) || MOCK_RESEARCH_ITEMS[0];
    setSelectedEvidenceItem(item);
  };

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* Header */}
      <div className="border-b border-slate-200 pb-4">
        <div className="flex items-center space-x-2 text-xs font-semibold text-emerald-700 uppercase tracking-wider mb-1">
          <Layers className="w-3.5 h-3.5 text-emerald-600" />
          <span>Evidence Traceability System</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">
          Evidence Explorer
        </h1>
        <p className="text-slate-600 text-sm mt-1">
          Trace the continuous validation chain connecting empirical field research to spatial datasets, policy formulations, and actionable insights.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex space-x-2 border-b border-slate-200">
        <button
          onClick={() => setActiveTab('Chain')}
          className={`pb-3 px-4 text-xs font-bold transition-all border-b-2 ${
            activeTab === 'Chain'
              ? 'border-emerald-600 text-emerald-800'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          Visual Evidence Chain
        </button>
        <button
          onClick={() => setActiveTab('Sources')}
          className={`pb-3 px-4 text-xs font-bold transition-all border-b-2 ${
            activeTab === 'Sources'
              ? 'border-emerald-600 text-emerald-800'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          Evidence Sources Matrix
        </button>
      </div>

      {activeTab === 'Chain' ? (
        <div className="space-y-6">
          {/* Visual Chain Banner */}
          <div className="bg-slate-900 text-white rounded-xl p-6 shadow-md">
            <div className="text-xs font-bold uppercase text-emerald-400 tracking-wider mb-2">
              End-to-End Governance Lineage
            </div>
            <h2 className="text-lg font-bold">Research → Dataset → GIS Evidence → Policy → Insight</h2>
            <p className="text-xs text-slate-300 mt-1 max-w-3xl">
              Every policy directive generated by LandInsight AI carries a verifiable lineage back to indexed empirical field studies and drone/satellite spatial datasets.
            </p>

            {/* Step Pipeline Visualization */}
            <div className="grid grid-cols-1 md:grid-cols-5 gap-3 mt-6">
              {MOCK_EVIDENCE_CHAIN.map((item, index) => (
                <div key={index} className="bg-slate-800/90 border border-slate-700 p-3.5 rounded-lg flex flex-col justify-between">
                  <div>
                    <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider mb-1">
                      {item.step}
                    </div>
                    <div className="text-xs font-bold text-white line-clamp-2">{item.title}</div>
                  </div>
                  <div className="mt-3 pt-2 border-t border-slate-700/80 text-[10px] text-slate-400 line-clamp-3">
                    {item.detail}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Interactive Indexed Evidence Repositories List */}
          <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-xs space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div>
                <h3 className="font-bold text-sm text-slate-900">Indexed Evidence Dossiers</h3>
                <p className="text-xs text-slate-500">Click "View Evidence" on any item to open the full 5-step lineage modal</p>
              </div>
              <span className="text-xs font-semibold px-2.5 py-1 bg-emerald-50 text-emerald-800 border border-emerald-200 rounded">
                5 Active Dossiers
              </span>
            </div>

            <div className="space-y-3">
              {MOCK_RESEARCH_ITEMS.map((item) => (
                <div
                  key={item.id}
                  className="p-4 bg-slate-50/70 rounded-xl border border-slate-200/90 hover:border-slate-300 transition-all flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
                >
                  <div className="space-y-1 flex-1">
                    <div className="flex items-center space-x-2 text-xs">
                      <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded font-semibold text-[10px]">
                        {item.type}
                      </span>
                      <span className="text-slate-400">•</span>
                      <span className="text-slate-600 font-medium">{item.organization}</span>
                      <span className="text-slate-400">•</span>
                      <span className="text-slate-500 font-medium">{item.year}</span>
                    </div>
                    <h4 className="font-bold text-slate-900 text-sm">{item.title}</h4>
                    <p className="text-slate-600 text-xs line-clamp-1">{item.description}</p>
                  </div>

                  <div className="flex items-center space-x-3 flex-shrink-0">
                    <span className="text-xs font-bold text-emerald-700 bg-white border border-emerald-200 px-2.5 py-1 rounded-md">
                      {item.relevance}% Match
                    </span>
                    <button
                      onClick={() => setSelectedEvidenceItem(item)}
                      className="px-3.5 py-2 bg-emerald-700 hover:bg-emerald-800 text-white rounded-lg text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-xs"
                    >
                      <span>View Evidence</span>
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        /* Sources Table */
        <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
          <div className="p-5 border-b border-slate-200 flex items-center justify-between">
            <div>
              <h3 className="font-bold text-sm text-slate-900">Indexed Evidence Sources</h3>
              <p className="text-xs text-slate-500">Credibility ratings and verification status for indexed repositories</p>
            </div>
            <span className="text-xs font-semibold px-2.5 py-1 bg-slate-100 text-slate-700 rounded">
              4 Primary Sources
            </span>
          </div>

          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-500 font-semibold border-b border-slate-200">
              <tr>
                <th className="py-3 px-4">Source Name</th>
                <th className="py-3 px-4">Type</th>
                <th className="py-3 px-4">Year</th>
                <th className="py-3 px-4">Credibility Status</th>
                <th className="py-3 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {sources.map((src, idx) => (
                <tr key={idx} className="hover:bg-slate-50/80 transition-colors">
                  <td className="py-3.5 px-4 font-bold text-slate-800">{src.name}</td>
                  <td className="py-3.5 px-4 text-slate-600">{src.type}</td>
                  <td className="py-3.5 px-4 text-slate-600">{src.year}</td>
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center space-x-1 px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded text-[10px] font-semibold">
                      <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                      <span>{src.status}</span>
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <button
                      onClick={() => handleOpenSourceModal(src.linkedId)}
                      className="px-3 py-1 bg-slate-900 hover:bg-slate-800 text-white rounded font-semibold text-[11px] inline-flex items-center space-x-1 transition-colors"
                    >
                      <span>View Source</span>
                      <ExternalLink className="w-3 h-3" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="p-4 bg-slate-50 text-[11px] text-slate-500 border-t border-slate-200">
            <strong>Note:</strong> Indexed sample sources are used for demonstration of the SIH 2026 prototype and do not claim official government affiliation unless explicitly marked.
          </div>
        </div>
      )}

      {/* Interactive Evidence Modal */}
      <EvidenceModal
        item={selectedEvidenceItem}
        onClose={() => setSelectedEvidenceItem(null)}
      />
    </div>
  );
};
